### ISSUE TITLE
Missing Depth Information for NYU Depth Dataset

### ISSUE THREAD

**Issue by coldmanck** [princeton-vl/SpatialSense#3]
Hi,

There are two image resources of your dataset: Flickr and NYU Depth. However, I can't find the depth information of those images from NYU Depth. Am I missing anything? Thank you!

Meng-Jiun

**Comment by yangky11** [comment]
We didn't change the filenames of the images. So you can find the depth information on the website of [NYU Depth](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html)
