### ISSUE TITLE
picture open wrong

### ISSUE THREAD

**Issue by simlexiaowan** [princeton-vl/SpatialSense#5]
How do I open a .nyu file and the picture opens wrong

**Comment by yangky11** [comment]
Could you please provide more details to reproduce the problem? Which file were you trying to open? And how did you open it?

**Comment by simlexiaowan** [comment]
I want to open the picture in .pang file format before the code runs, and double-click directly to display the file error.

Excuse me, can't I double-click to open the image under the image.tar.gz file?

**Comment by yangky11** [comment]
You should be able to do that after unzipping image.tar.gz. Could you please a specific file name that you tried to open? I can try it on my computer.

**Comment by simlexiaowan** [comment]
I tried it on myself and my dad's computer. I think it's a problem of file download. Recently, China's VPN access to external networks is very unstable. If it is convenient, can you post the datasets or  image.tar.gz file directly? Email: 19120413@bjtu.edu.cn

**Comment by yangky11** [comment]
I would like to do so but I'm afraid that the file is too large to be transferred via email.

**Comment by simlexiaowan** [comment]
OK, I will try downloading again. Thank you

**Comment by simlexiaowan** [comment]
ok
