### ISSUE TITLE
Some questions about spatial sense

### ISSUE THREAD

**Issue by forbiddenname** [princeton-vl/SpatialSense#6]
Dear author：
Thank you for your awesome code！It will help me a lot, but i have some questions.
1. If I have only one picture and no groundtruth, do I need to do object detection first to get labels and boundingboxs? then how to detect the spatial relations of this picture with the predicated labels and predicated boundingbox.
2. Which of these relationship detection models is the fastest and whether it can be real-time?
Thanks!!!!!!!

**Comment by forbiddenname** [comment]
> Hi,
> 
> Thanks for your interest in our work.
> 
>     1. Yes, you have to run object detection first. We didn't provide a direct interface to run spatial relation recognition on a single image provided by the user. So you may have to change the code in order to do that. You could save the object detection results in the same format as the SpatialSense dataset and then try to run the baseline models.
> 
>     2. We didn't benchmark the speed of the baseline models. Nor did we aim for real-time spatial relation recognition. However, you could run the baselines to see which one is faster.
thanks!!!!

> Hi,
> 
> Thanks for your interest in our work.
> 
>     1. Yes, you have to run object detection first. We didn't provide a direct interface to run spatial relation recognition on a single image provided by the user. So you may have to change the code in order to do that. You could save the object detection results in the same format as the SpatialSense dataset and then try to run the baseline models.
> 
>     2. We didn't benchmark the speed of the baseline models. Nor did we aim for real-time spatial relation recognition. However, you could run the baselines to see which one is faster.

HI, Thank you very much. I have another question. Is it possible for us to obtain the spatial relationship annotation tool in Figure 2 of this article.

**Comment by forbiddenname** [comment]
> Hi,
> 
> Thanks for your interest in our work.
> 
>     1. Yes, you have to run object detection first. We didn't provide a direct interface to run spatial relation recognition on a single image provided by the user. So you may have to change the code in order to do that. You could save the object detection results in the same format as the SpatialSense dataset and then try to run the baseline models.
> 
>     2. We didn't benchmark the speed of the baseline models. Nor did we aim for real-time spatial relation recognition. However, you could run the baselines to see which one is faster.

HI, Thank you very much. I have another question. Is it possible for us to obtain the spatial relationship annotation tool in Figure 2 of this article.

**Comment by yangky11** [comment]
We didn't include the UI code in the repo because it is a little bit messy and not in a releasable state. However, I can send you the code via email if you need it.

**Comment by forbiddenname** [comment]
> We didn't include the UI code in the repo because it is a little bit messy and not in a releasable state. However, I can send you the code via email if you would like to. 

it‘s great！！ 
my email： lixin314@foxmail.com

**Comment by forbiddenname** [comment]
Sorry, there is another question ^_^. Have you tested the effect of depth information on spatial relationship detection?  It should be very helpful.

**Comment by yangky11** [comment]
I just sent you the code via email.

Unfortunately, we didn't include experiments about depth information in the paper.

**Comment by forbiddenname** [comment]
> I just sent you the code via email.
> 
> Unfortunately, we didn't include experiments about depth information in the paper.

thank you！！！
