### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by moutaigua8183** [princeton-vl/SpatialSense#7]
Hi there,   thanks for the great work. Just a kind suggestion:  it would be very helpful if the authors can provide a guide for installation, or a requirement.txt file.
Before I can successfully run your code,  I spent some time to figure out the correct Python libraries and their versions, e.g.    
* pip install progressbar2,   not progressbar;
* from autocorrect import spell    -->    from autocorrect import Speller  &    insert "spell = Speller()" at line 23 in util.py.

**Comment by yangky11** [comment]
Hi,

Sorry for the confusion about progress2. Sure, that's a great suggestion! I'll add a conda file to the repo.

**Comment by moutaigua8183** [comment]
Thanks for the promt response. But it seems that a warning with autocorrect has not been solved.  I would recommand specifying the very version you use for __autocorrect__ package. My latest version (2.3.0) will keep printing a warning saying that the __spell__ from
```python
from autocorrect import spell
```
is deprecated, and it greatly affects the user experience.    Otherwise, please update the util.py as follows
```python
 from autocorrect import Speller    #Originally, from autocorrect import spell
...
spell = Speller() # insert after line 23
```

**Comment by yangky11** [comment]
fixed
